steps:
  - label: Build cocoa IPA
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac
    artifact_paths: features/fixtures/ios-swift-cocoapods/output/*
    commands:
      - ./features/scripts/export_ios_app.sh

  - wait

  - label: ':ios: iOS 13 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.2.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v2.6.0:
        run: cocoa-maze-runner
    env:
      DEVICE_TYPE: IOS_13
    concurrency: 5
    concurrency_group: browserstack-app

  - block: Trigger full test suite

  - label: ':ios: iOS 12 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.2.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v2.6.0:
        run: cocoa-maze-runner
    env:
      DEVICE_TYPE: IOS_12
    concurrency: 5
    concurrency_group: browserstack-app

  - label: ':ios: iOS 11 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.2.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v2.6.0:
        run: cocoa-maze-runner
    env:
      DEVICE_TYPE: IOS_11
    concurrency: 5
    concurrency_group: browserstack-app

  - label: ':ios: iOS 10 end-to-end tests'
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.2.0:
        download: ["features/fixtures/ios-swift-cocoapods/output/iOSTestApp.ipa"]
      docker-compose#v2.6.0:
        run: cocoa-maze-runner
    env:
      DEVICE_TYPE: IOS_10
    concurrency: 5
    concurrency_group: browserstack-app
