language: objective-c
matrix:
    include:
        - osx_image: xcode7.2
          env: IPHONE_SDK=iphonesimulator9.2
        - osx_image: xcode6.1
          env: IPHONE_SDK=iphonesimulator8.1
        - osx_image: xcode6.1
          env: IPHONE_SDK=iphonesimulator7.1
        - osx_image: xcode6.1
          env: IPHONE_SDK=iphonesimulator7.0
install: make bootstrap
script: make test
