version: '3.6'
services:
  cocoa-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cocoa
    environment:
      VERBOSE:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      DEVICE_TYPE:
      APP_LOCATION:
    command: --tags "not @wip"
    volumes:
      - ./test-fixture/ios-swift-cocoapods/output:/app/build
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true